/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym;

import java.awt.Color;

/**
 *
 * @author Axel_
 */
public class gym extends javax.swing.JFrame {

    /**
     * Creates new form gym
     */
    public gym() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        panelLateral1 = new javax.swing.JPanel();
        clientes_bot = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rutinas_bot = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        productos_bot = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cuotas_bot = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ventas_bot = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ayuda_bot = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        salir_bot = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        inicio = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        panelClientes = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        panelRutinas = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        panelCuotas = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        panelAyuda = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        panelVentas = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        bg1.setBackground(new java.awt.Color(204, 204, 204));
        bg1.setForeground(new java.awt.Color(255, 255, 255));
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLateral1.setBackground(new java.awt.Color(102, 102, 102));
        panelLateral1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientes_bot.setBackground(new java.awt.Color(153, 153, 153));
        clientes_bot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                clientes_botMouseMoved(evt);
            }
        });
        clientes_bot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientes_botMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientes_botMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        jLabel6.setText("CLIENTES");

        javax.swing.GroupLayout clientes_botLayout = new javax.swing.GroupLayout(clientes_bot);
        clientes_bot.setLayout(clientes_botLayout);
        clientes_botLayout.setHorizontalGroup(
            clientes_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientes_botLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        clientes_botLayout.setVerticalGroup(
            clientes_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientes_botLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelLateral1.add(clientes_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        rutinas_bot.setBackground(new java.awt.Color(153, 153, 153));
        rutinas_bot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rutinas_botMouseMoved(evt);
            }
        });
        rutinas_bot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rutinas_botMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rutinas_botMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/documentos.png"))); // NOI18N
        jLabel8.setText("RUTINAS");

        javax.swing.GroupLayout rutinas_botLayout = new javax.swing.GroupLayout(rutinas_bot);
        rutinas_bot.setLayout(rutinas_botLayout);
        rutinas_botLayout.setHorizontalGroup(
            rutinas_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rutinas_botLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        rutinas_botLayout.setVerticalGroup(
            rutinas_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutinas_botLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelLateral1.add(rutinas_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        productos_bot.setBackground(new java.awt.Color(153, 153, 153));
        productos_bot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                productos_botMouseMoved(evt);
            }
        });
        productos_bot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productos_botMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productos_botMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productos.png"))); // NOI18N
        jLabel10.setText("PRODUCTOS");

        javax.swing.GroupLayout productos_botLayout = new javax.swing.GroupLayout(productos_bot);
        productos_bot.setLayout(productos_botLayout);
        productos_botLayout.setHorizontalGroup(
            productos_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productos_botLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        productos_botLayout.setVerticalGroup(
            productos_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productos_botLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelLateral1.add(productos_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        cuotas_bot.setBackground(new java.awt.Color(153, 153, 153));
        cuotas_bot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cuotas_botMouseMoved(evt);
            }
        });
        cuotas_bot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuotas_botMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cuotas_botMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuotas.png"))); // NOI18N
        jLabel2.setText("CUOTAS");

        javax.swing.GroupLayout cuotas_botLayout = new javax.swing.GroupLayout(cuotas_bot);
        cuotas_bot.setLayout(cuotas_botLayout);
        cuotas_botLayout.setHorizontalGroup(
            cuotas_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuotas_botLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        cuotas_botLayout.setVerticalGroup(
            cuotas_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuotas_botLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelLateral1.add(cuotas_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        ventas_bot.setBackground(new java.awt.Color(153, 153, 153));
        ventas_bot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ventas_botMouseMoved(evt);
            }
        });
        ventas_bot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventas_botMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ventas_botMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N
        jLabel14.setText("VENTAS");

        javax.swing.GroupLayout ventas_botLayout = new javax.swing.GroupLayout(ventas_bot);
        ventas_bot.setLayout(ventas_botLayout);
        ventas_botLayout.setHorizontalGroup(
            ventas_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventas_botLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        ventas_botLayout.setVerticalGroup(
            ventas_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventas_botLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelLateral1.add(ventas_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        ayuda_bot.setBackground(new java.awt.Color(153, 153, 153));
        ayuda_bot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ayuda_botMouseMoved(evt);
            }
        });
        ayuda_bot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ayuda_botMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ayuda_botMouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayuda (1).png"))); // NOI18N
        jLabel16.setText("AYUDA");

        javax.swing.GroupLayout ayuda_botLayout = new javax.swing.GroupLayout(ayuda_bot);
        ayuda_bot.setLayout(ayuda_botLayout);
        ayuda_botLayout.setHorizontalGroup(
            ayuda_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ayuda_botLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        ayuda_botLayout.setVerticalGroup(
            ayuda_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ayuda_botLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelLateral1.add(ayuda_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        salir_bot.setBackground(new java.awt.Color(153, 153, 153));
        salir_bot.setForeground(new java.awt.Color(255, 255, 255));
        salir_bot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                salir_botMouseMoved(evt);
            }
        });
        salir_bot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salir_botMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salir_botMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        jLabel12.setText("SALIR");

        javax.swing.GroupLayout salir_botLayout = new javax.swing.GroupLayout(salir_bot);
        salir_bot.setLayout(salir_botLayout);
        salir_botLayout.setHorizontalGroup(
            salir_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salir_botLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        salir_botLayout.setVerticalGroup(
            salir_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salir_botLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelLateral1.add(salir_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, -1, -1));

        inicio.setBackground(new java.awt.Color(153, 153, 153));
        inicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                inicioMouseMoved(evt);
            }
        });
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jLabel11.setText("INICIO");

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelLateral1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        bg1.add(panelLateral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 770));

        jPanel2.setBackground(new java.awt.Color(86, 7, 12));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tu gimnasio bien administrado");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("SMART GYM");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 662, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        bg1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1160, 140));

        panelInicio.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", panelInicio);

        panelClientes.setBackground(new java.awt.Color(204, 204, 204));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel28.setText("CLIENTES");

        jTable2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(86, 7, 12), new java.awt.Color(86, 7, 12), new java.awt.Color(86, 7, 12), new java.awt.Color(86, 7, 12)));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nehemias Rubio", "2604698259", "41775121", "Maza 1875"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre y Apellido", "Teléfono", "DNI", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(86, 7, 12));
        jTable2.setRowHeight(30);
        jTable2.setSelectionBackground(new java.awt.Color(86, 7, 12));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nombre y apellido:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Teléfono:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("DNI:");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AGREGAR");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("MODIFICAR");
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ELIMINAR");
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel34.setText("DATOS");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Dirección:");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(136, 136, 136))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel34))
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(53, 53, 53)
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", panelClientes);

        panelRutinas.setBackground(new java.awt.Color(204, 204, 204));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel29.setText("RUTINAS");

        javax.swing.GroupLayout panelRutinasLayout = new javax.swing.GroupLayout(panelRutinas);
        panelRutinas.setLayout(panelRutinasLayout);
        panelRutinasLayout.setHorizontalGroup(
            panelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutinasLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        panelRutinasLayout.setVerticalGroup(
            panelRutinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutinasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel29)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", panelRutinas);

        panelProductos.setBackground(new java.awt.Color(204, 204, 204));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel30.setText("PRODUCTOS");

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel30)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", panelProductos);

        panelCuotas.setBackground(new java.awt.Color(204, 204, 204));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel31.setText("CUOTAS");

        javax.swing.GroupLayout panelCuotasLayout = new javax.swing.GroupLayout(panelCuotas);
        panelCuotas.setLayout(panelCuotasLayout);
        panelCuotasLayout.setHorizontalGroup(
            panelCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuotasLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        panelCuotasLayout.setVerticalGroup(
            panelCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuotasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel31)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", panelCuotas);

        panelAyuda.setBackground(new java.awt.Color(204, 204, 204));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel32.setText("AYUDA");

        javax.swing.GroupLayout panelAyudaLayout = new javax.swing.GroupLayout(panelAyuda);
        panelAyuda.setLayout(panelAyudaLayout);
        panelAyudaLayout.setHorizontalGroup(
            panelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAyudaLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        panelAyudaLayout.setVerticalGroup(
            panelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAyudaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel32)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab7", panelAyuda);

        panelVentas.setBackground(new java.awt.Color(204, 204, 204));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel33.setText("VENTAS");

        javax.swing.GroupLayout panelVentasLayout = new javax.swing.GroupLayout(panelVentas);
        panelVentas.setLayout(panelVentasLayout);
        panelVentasLayout.setHorizontalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        panelVentasLayout.setVerticalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel33)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", panelVentas);

        bg1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 1080, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clientes_botMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientes_botMouseMoved
        clientes_bot.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_clientes_botMouseMoved

    private void clientes_botMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientes_botMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_clientes_botMouseClicked

    private void clientes_botMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientes_botMouseExited
        clientes_bot.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_clientes_botMouseExited

    private void rutinas_botMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rutinas_botMouseMoved
        rutinas_bot.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_rutinas_botMouseMoved

    private void rutinas_botMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rutinas_botMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_rutinas_botMouseClicked

    private void rutinas_botMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rutinas_botMouseExited
        rutinas_bot.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_rutinas_botMouseExited

    private void productos_botMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productos_botMouseMoved
        productos_bot.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_productos_botMouseMoved

    private void productos_botMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productos_botMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_productos_botMouseClicked

    private void productos_botMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productos_botMouseExited
        productos_bot.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_productos_botMouseExited

    private void cuotas_botMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuotas_botMouseMoved
        cuotas_bot.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_cuotas_botMouseMoved

    private void cuotas_botMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuotas_botMouseClicked
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_cuotas_botMouseClicked

    private void cuotas_botMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuotas_botMouseExited
        cuotas_bot.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_cuotas_botMouseExited

    private void ventas_botMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventas_botMouseMoved
        ventas_bot.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_ventas_botMouseMoved

    private void ventas_botMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventas_botMouseClicked
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_ventas_botMouseClicked

    private void ventas_botMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventas_botMouseExited
        ventas_bot.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_ventas_botMouseExited

    private void ayuda_botMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayuda_botMouseMoved
        ayuda_bot.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_ayuda_botMouseMoved

    private void ayuda_botMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayuda_botMouseClicked
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_ayuda_botMouseClicked

    private void ayuda_botMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayuda_botMouseExited
        ayuda_bot.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_ayuda_botMouseExited

    private void salir_botMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir_botMouseMoved
        salir_bot.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_salir_botMouseMoved

    private void salir_botMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir_botMouseClicked
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_salir_botMouseClicked

    private void salir_botMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir_botMouseExited
        salir_bot.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_salir_botMouseExited

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        jButton1.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        jButton2.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        jButton3.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton3MouseExited

    private void inicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseMoved
        inicio.setBackground(new Color(86, 7, 12));
    }//GEN-LAST:event_inicioMouseMoved

    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_inicioMouseClicked

    private void inicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseExited
        inicio.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_inicioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gym().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ayuda_bot;
    private javax.swing.JPanel bg1;
    private javax.swing.JPanel clientes_bot;
    private javax.swing.JPanel cuotas_bot;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panelAyuda;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelCuotas;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelLateral1;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelRutinas;
    private javax.swing.JPanel panelVentas;
    private javax.swing.JPanel productos_bot;
    private javax.swing.JPanel rutinas_bot;
    private javax.swing.JPanel salir_bot;
    private javax.swing.JPanel ventas_bot;
    // End of variables declaration//GEN-END:variables
}
